wordpress:
  image: wordpress
  links:
    - mariadb:mysql
  environment:
    - WORDPRESS_DB_PASSWORD=password
  ports:
    - '80:80'
  volumes:
    - ./html:/var/www/html
mariadb:
  image: mariadb:10.0.33
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=wordpress
  volumes:
    - ./data:/var/lib/mysql
